In [54]:
# by shubham import all libraries 

# Data manipultaion and visualization 

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import math as m

# Here Ml libraries are imported 

# type of (macors)  to set various option  
pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 150)
pd.set_option('display.max_seq_items', None)
 
#%config InlineBackend.figure_formats = {'pdf',}
%matplotlib inline

# for effctive visualiztion 
import seaborn as sns
sns.set_context('notebook')
sns.set_style('white')

In [55]:
data=pd.read_csv('sample gps data with few columns.csv')

In [60]:
#data.drop(['data_status','vehicle_direction'],axis=1)
#date,time =data['ist_date'].split()
data['Dates'] = pd.to_datetime(data['ist_date']).dt.date
data['Time'] = pd.to_datetime(data['ist_date']).dt.time
data.columns

Index(['device_id', 'data_status', 'lat', 'lng', 'speed_kmph', 'ist_date',
       'Dates', 'Time'],
      dtype='object')

In [71]:
# here specific feild selected 
#data.drop['0','1']
# top three has diffent from every 10 sec data 
# i.e. drop these row
data=data.iloc[6:]

In [75]:
# data is in proper format 
data[['speed_kmph','Dates','Time']]

      speed_kmph       Dates      Time
7              0  2016-06-01  01:15:00
8              0  2016-06-01  01:15:00
9              0  2016-06-01  01:15:00
10             0  2016-06-01  01:15:00
11             0  2016-06-01  01:15:00
12             0  2016-06-01  01:15:00
13             0  2016-06-01  01:16:00
14             0  2016-06-01  01:16:00
15             0  2016-06-01  01:16:00
16             0  2016-06-01  01:16:00
17             0  2016-06-01  01:16:00
18             0  2016-06-01  01:16:00
19             0  2016-06-01  01:17:00
20             0  2016-06-01  01:17:00
21             0  2016-06-01  01:17:00
22             0  2016-06-01  01:17:00
23             0  2016-06-01  01:17:00
24             0  2016-06-01  01:17:00
25             0  2016-06-01  01:18:00
26             0  2016-06-01  01:18:00
27             0  2016-06-01  01:18:00
28             0  2016-06-01  01:18:00
29             0  2016-06-01  01:18:00
30             0  2016-06-01  01:18:00
31             0  2016-06-01  01:19:00
32             0  2016-06-01  01:19:00
33             0  2016-06-01  01:19:00
34             0  2016-06-01  01:19:00
35             0  2016-06-01  01:19:00
36             0  2016-06-01  01:19:00
37             0  2016-06-01  01:20:00
38             0  2016-06-01  01:20:00
39             0  2016-06-01  01:20:00
40             0  2016-06-01  01:20:00
41             0  2016-06-01  01:20:00
42             0  2016-06-01  01:20:00
43             0  2016-06-01  01:21:00
44             0  2016-06-01  01:21:00
45             0  2016-06-01  01:21:00
46             0  2016-06-01  01:21:00
47             0  2016-06-01  01:21:00
48             6  2016-06-01  01:21:00
49             0  2016-06-01  01:22:00
50             0  2016-06-01  01:22:00
51             0  2016-06-01  01:22:00
52             0  2016-06-01  01:22:00
53             0  2016-06-01  01:22:00
54             0  2016-06-01  01:22:00
55             0  2016-06-01  01:23:00
56             0  2016-06-01  01:23:00
57             0  2016-06-01  01:23:00
58             0  2016-06-01  01:23:00
59             0  2016-06-01  01:23:00
60             0  2016-06-01  01:23:00
61             0  2016-06-01  01:23:00
62             0  2016-06-01  01:24:00
63             6  2016-06-01  01:24:00
64             6  2016-06-01  01:24:00
65             5  2016-06-01  01:24:00
66             0  2016-06-01  01:24:00
67             0  2016-06-01  01:24:00
68             0  2016-06-01  01:25:00
69             0  2016-06-01  01:25:00
70             0  2016-06-01  01:25:00
71             0  2016-06-01  01:25:00
72             0  2016-06-01  01:25:00
73             0  2016-06-01  01:25:00
74             0  2016-06-01  01:26:00
75             0  2016-06-01  01:26:00
76             0  2016-06-01  01:26:00
77             0  2016-06-01  01:26:00
78             0  2016-06-01  01:26:00
79             0  2016-06-01  01:26:00
80             0  2016-06-01  01:27:00
81             0  2016-06-01  01:27:00
...          ...         ...       ...
4187           0  2016-06-01  15:06:00
4188          24  2016-06-01  15:06:00
4189          12  2016-06-01  15:06:00
4190          33  2016-06-01  15:06:00
4191          46  2016-06-01  15:06:00
4192          55  2016-06-01  15:06:00
4193          56  2016-06-01  15:07:00
4194          58  2016-06-01  15:07:00
4195          53  2016-06-01  15:07:00
4196           0  2016-06-01  15:07:00
4197          18  2016-06-01  15:07:00
4198          36  2016-06-01  15:07:00
4199          56  2016-06-01  15:08:00
4200          58  2016-06-01  15:08:00
4201          57  2016-06-01  15:08:00
4202          49  2016-06-01  15:08:00
4203           0  2016-06-01  15:08:00
4204          16  2016-06-01  15:08:00
4205          34  2016-06-01  15:09:00
4206          47  2016-06-01  15:09:00
4207          51  2016-06-01  15:09:00
4208          50  2016-06-01  15:09:00
4209          51  2016-06-01  15:09:00
4210          53  2016-06-01  15:09:00
4211          53  2016-06-01  15:10:00
4212          41  2016-06-01  15:10:00
4213          45  2016-06-01  15:10:00
4214          52  2016-06-01  15:10:00
4215          53  2016-06-01  15:10:00
4216          54  2016-06-01  15:10:00
4217          40  2016-06-01  15:11:00
4218          41  2016-06-01  15:11:00
4219          46  2016-06-01  15:11:00
4220          41  2016-06-01  15:11:00
4221          13  2016-06-01  15:11:00
4222          10  2016-06-01  15:11:00
4223           0  2016-06-01  15:12:00
4224           0  2016-06-01  15:12:00
4225           0  2016-06-01  15:12:00
4226          14  2016-06-01  15:12:00
4227           0  2016-06-01  15:12:00
4228          19  2016-06-01  15:12:00
4229          27  2016-06-01  15:13:00
4230          35  2016-06-01  15:13:00
4231          39  2016-06-01  15:13:00
4232          40  2016-06-01  15:13:00
4233          42  2016-06-01  15:13:00
4234          40  2016-06-01  15:13:00
4235           8  2016-06-01  15:14:00
4236          24  2016-06-01  15:14:00
4237          36  2016-06-01  15:14:00
4238          33  2016-06-01  15:14:00
4239          43  2016-06-01  15:14:00
4240          46  2016-06-01  15:14:00
4241          34  2016-06-01  15:15:00
4242           0  2016-06-01  15:15:00
4243          21  2016-06-01  15:15:00
4244          33  2016-06-01  15:15:00
4245          43  2016-06-01  15:15:00
4246          47  2016-06-01  15:15:00
4247          44  2016-06-01  15:16:00
4248          50  2016-06-01  15:16:00
4249          55  2016-06-01  15:16:00
4250          57  2016-06-01  15:16:00
4251          55  2016-06-01  15:16:00
4252          54  2016-06-01  15:16:00
4253          56  2016-06-01  15:17:00
4254          58  2016-06-01  15:17:00
4255          56  2016-06-01  15:17:00
4256          57  2016-06-01  15:17:00
4257          50  2016-06-01  15:17:00
4258          39  2016-06-01  15:17:00
4259          26  2016-06-01  15:18:00
4260           0  2016-06-01  15:18:00
4261          11  2016-06-01  15:18:00

[4255 rows x 3 columns]